### ISSUE TITLE
模型BertCRF_pre权重保存出错 - save_pretrained

### ISSUE THREAD

**Issue by qiutzh** [shenzaimin/CCKS2020Task4-3rd#2]
@shenzaimin 请问，您有遇到这个错误吗：
```shell
Traceback (most recent call last):
  File "//home/test/program/ee/transfer_train_roberta_model_aug.py", line 1340, in <module>
    pretrain_main()
  File "//home/test/program/ee/transfer_train_roberta_model_aug.py", line 588, in pretrain_main
    trans_model_to_save.save_pretrained(model_name)
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/transformers/modeling_utils.py", line 504, in save_pretrained
    model_to_save.config.save_pretrained(save_directory)
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 141, in save_pretrained
    self.to_json_file(output_config_file, use_diff=True)
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 397, in to_json_file
    writer.write(self.to_json_string(use_diff=use_diff))
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 384, in to_json_string
    return json.dumps(config_dict, indent=2, sort_keys=True) + "\n"
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/anaconda3/envs/py3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'device' is not JSON serializable

```

Debug发现：
```shell
def to_json_file(self, json_file_path, use_diff=True):
    with open(json_file_path, "w", encoding="utf-8") as writer:
        writer.write(self.to_json_string(use_diff=use_diff))

def to_json_string(self):
	return json.dumps(self.to_dict(), indent=2, sort_keys=True) + "\n"

# 执行 `json.dumps(self.to_dict(), indent=2, sort_keys=True)` 时报的错
print(self.to_dict())
# {'output_attentions': False, 'output_hidden_states': False, ... , 'device': device(type='cuda'), 'label2idx': {...}}
```
错在 ** 'device': device(type='cuda') ** 这个键值对，您知道怎么修改吗！

**Comment by shenzaimin** [comment]
进入到transformer（我的版本号3.0.2）包内部的modeling_utils.py 中的第504行注释掉
也就是save_pretrained(self, save_directory)方法里的这一行（model_to_save.config.save_pretrained(save_directory)）

**Comment by qiutzh** [comment]
谢谢您^_^
